oc_louvre_homepage:
    path:     /
    defaults: { _controller: OCLouvreBundle:Default:index }

oc_louvre_newCommande:
    path:     /order
    defaults: { _controller: OCLouvreBundle:Default:newCommande }