services:
#    oc_louvre.example:
#        class: OC\LouvreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    oc_louvre.calculprice:
        class: OC\LouvreBundle\Service\CalculPrice
        arguments:
            - %prices%

    oc_louvre.email_commande:
        class: OC\LouvreBundle\Service\EmailCommande
        arguments: ["@mailer", '@twig']

    oc_louvre.stripe_payement:
        class: OC\LouvreBundle\Service\StripePayement
